### PR TITLE
Insertion changelog generator gets git pat from git credential

### PR DESCRIPTION
**Pull request by zivkan**
I'm too lazy to pass the PAT on the command line.

### CODE REVIEW

**Comment by zivkan** [comment]
@nkolev92 any idea why I can't add @NuGet/nuget-client  as a reviewer in this repo?

**Comment by nkolev92** [comment]
NuGet.Client does not have any permissions for this repo. 

Let me add it.

**Comment by nkolev92** [comment]
Try now.

**Review by nkolev92 — APPROVED** [review]
looks good, please change the readme as well.

**Pull request merged**
